data:
  image: busybox
  volumes:
    - /data:/data
    - /garesco:/garesco

rethinkdb:
  image: rethinkdb
  volumes_from:
   - data
  ports:
   - "28015:28015"
   - "8080:8080"

server:
  image: google/dart:1.11.3
  volumes_from:
    - data
  links:
    - db
  ports:
    - "80:9090"
  command: bash -c "cd /garesco && pub get && dart bin/server.dart"