name: garesco_email
description: A sample web application
dependencies:
  cookies: any
  mustache: any
  path: any
  quiver: any
  redstone: '>=0.6.0-beta.1+3 < 0.7.0'
  redstone_mapper: '>=0.2.0-beta.1 < 0.3.0'
  redstone_rethinkdb: '>=0.1.0-beta.1+1'
  redstone_mapper_mongo: '>=0.2.0-beta.1'
  rethinkdb_driver: 2.0.1+1
  postgresql: any
  uuid: any
  redstone_mvc: '>=0.1.0-beta.1+8'
  shelf: '>=0.6.0 <0.7.0'
  shelf_static: any
  di: any
