name: garesco_email
description: A sample web application
dependencies:
  cookies: any
  mustache: any
  path: any
  quiver: any
  redstone: "< 0.6.0"
  redstone_mapper: any
  redstone_rethinkdb: any
  rethinkdb_driver: any
  postgresql: any
  uuid: any
  redstone_mvc: ">=0.0.380+2 < 0.1.0"
  shelf: any
  shelf_static: any
  redstone_utilities: any
  di: any
  browser: any
transformers:
- redstone_mapper
